framework:
    secret: secret

doctrine:
    dbal:
        driver:   pdo_sqlite
        path: %kernel.root_dir%/app.sqlite
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"
    orm:

doctrine_phpcr:
    session:
        backend:
            type: doctrinedbal
        workspace: default
        username: admin
        password: admin
    odm:

psi_object_agent:
    enabled_agents:
        - doctrine_orm
        - doctrine_phpcr_odm
